<?php class Gotop_CitySelector_Block_Adminhtml_Index extends Mage_Adminhtml_Block_Abstract
{
    public function _toHtml()
    {
        echo 'Fuck Off!';
        return parent::_toHtml(); // TODO: Change the autogenerated stub
    }
}